# Generated by Django 6.0.3 on 2026-03-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('oncology', 'Oncology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('emergency', 'Emergency Medicine'), ('general', 'General Medicine'), ('surgery', 'General Surgery'), ('ent', 'ENT'), ('ophthalmology', 'Ophthalmology'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('gastroenterology', 'Gastroenterology'), ('urology', 'Urology'), ('anesthesiology', 'Anesthesiology'), ('other', 'Other')], default='general', max_length=50)),
                ('qualifications', models.CharField(blank=True, help_text='e.g. MBBS, MD, DM (Cardiology)', max_length=300)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'In Consultation'), ('on_leave', 'On Leave'), ('off_duty', 'Off Duty')], default='available', max_length=20)),
                ('timing_start', models.TimeField(help_text='Consultation start time')),
                ('timing_end', models.TimeField(help_text='Consultation end time')),
                ('available_days', models.CharField(choices=[('Mon-Fri', 'Monday to Friday'), ('Mon-Sat', 'Monday to Saturday'), ('Mon-Sun', 'All Days'), ('Mon,Wed,Fri', 'Mon / Wed / Fri'), ('Tue,Thu,Sat', 'Tue / Thu / Sat'), ('Weekdays', 'Weekdays Only'), ('Weekends', 'Weekends Only')], default='Mon-Sat', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.hospital')),
            ],
            options={
                'ordering': ['specialization', 'name'],
            },
        ),
    ]
